### ISSUE TITLE
kafka output type missing in config.go

### ISSUE THREAD

**Issue by dstruck** [carbonblack/cb-event-forwarder#133]
Hello,

Setting `output_type: kafka` in the config file gives the following error message:

> FATA[0000] Configuration errors:
>  Unknown output type: kafka

**config.go** does not support the Kafka option anymore.

Is Kafka support deprecated or will it be re-added in the future?

Best regards,
Daniel

**Comment by zacharyestep** [comment]
Hi dan,

Kafka support is not deprecated, we're moving to (dev is pretty well done) from sarama to using the librdkafka.so bindings in golang provided by confluent.io in order to provide more robust support (sarama  lib is wonderful but exhibited a host of issues for particular broker versions/configurations) - 

additionally, with there is a new architecture for the soon-to-come 4.0 release - supporting output plugins / types that dont require upstream contributions to the codebase and can be maintained by users of the event forwarder.  The existing 'kafka' output type has been reworked into a standard plugin that can be loaded like : output_type: plugin and providing the relevant plugin information. 

V/r,
ZE

**Comment by dstruck** [comment]
Sounds great. Looking forward to test the new version.

**Comment by dstruck** [comment]
When I try to start the new beta with the "-check" option I get the following error message:

> INFO[0000] Found 1 ouputs...
> INFO[0000] Starting Cb Event Forwarder cb-event-forwarder
> INFO[0000] Configured to remove keys: []
> INFO[0000] Configured to add k-vs to output: map[]
> INFO[0000] cb-event-forwarder 4.0.0 BETA starting
> INFO[0000] Interface address xxx.xxx.xxx.xxx
> INFO[0000] Interface address xxxx::xxxx:xxxx:xxxx:xxxx
> INFO[0000] Trying to start output %!s(<nil>)
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc6cc08]
> 
> goroutine 1 [running]:
> github.com/carbonblack/cb-event-forwarder/internal/cbeventforwarder.(*CbEventForwarder).StartOutputs(0xc420278300, 0x14, 0xc420251cd8)
>         /home/xxxx/cb4beta/src/github.com/carbonblack/cb-event-forwarder/internal/cbeventforwarder/cbeventforwarder.go:170 +0x2f8
> main.main()
>         /home/xxxx/cb4beta/src/github.com/carbonblack/cb-event-forwarder/cmd/cb-event-forwarder/main.go:100 +0xb9c
