### ISSUE TITLE
Wrong segment ID for LEEF output in netconn events

### ISSUE THREAD

**Issue by adamsmutnicki** [carbonblack/cb-event-forwarder#50]
In case of processes with a lot of netconn events, a LEEF output of a corresponding netconn contains a link to a segment 1, while this particular netconn is at other segment id.

With a following LEEF:
LEEF:1.0|CB|CB|5.1|ingress.event.netconn|cb_server=cbserver computer_name=HOSTNAME direction=inbound domain= dst=IP.180 dstPort=41447 event_type=netconn ipv4=IP.180 link_process=https://CB-SERVER/#analyze/00000014-0000-0ccc-01d1-85424831d984/1 local_ip=IP.243 local_port=443 md5=3A31ECC4DD96E63D4193FD13CE2233C3 pid=3276 port=443 process_guid=00000014-0000-0ccc-01d1-85424831d984 proto=6 protocol=6 remote_ip=IP.180 remote_port=41447 sensor_id=20 src=IP.243 srcPort=443 timestamp=1469447484 type=ingress.event.netcon

I was able to find a given netconn event in the GUI under segment id 389 (I had to look for it manually), 
https://CB-SERVER/#/analyze/00000014-0000-0ccc-01d1-85424831d984/389/cb.urlver=1&q=process_name%3Awspsrv.exe%20sensor_id%3A20&sort=start%20desc&rows=10&start=0

**Comment by jgarman** [comment]
Yes, unfortunately there is no way to generate the segment ID automatically (segments are generated every 10,000 events by default). Since the segment is not sent as part of the event and is assigned by the server when the data is stored to the database, we don't have access to it.

Two things should happen: 1) we need to make clear the limitations of the process link, and 2) we can (potentially) try and estimate the segment ID if we receive all the events for a process.

Another option may be to generate a search link instead of a direct process link, would that make sense in your use case? In your case try this query in Cb:

```
process_id:00000014-0000-0ccc-01d1-85424831d984 ipaddr:IP.180
```

Does that pull up the relevant segment?

Thanks!

**Comment by adamsmutnicki** [comment]
Hi,
I've checked the query you proposed, and the problem with such approach in this case, is that the search provides 285 results. This means, that this IP have been seen multiple times in probably 285 segments of this process. As you see, this was not very helpful in reaching out particular process segment. I'm thinking about other distinguishable factors: 
* can we somehow use the netconn timestamp to narrow search results?
* if we could search for tcp src/dst port numbers, I believe this would be sufficient to probably get a single result. I think that such operators are not present in CB, but personally I believe they would be helpful. 
Regards
Adam

**Comment by jgarman** [comment]
Hey Adam,

Thanks for your reply. The timestamp is tricky since the Cb query language does not allow you to search for events, but rather processes (regardless of the number of "segments" that process may have been sliced into). Cb does have the ability to search for dst port numbers as of 5.1, but not src port numbers. The operator is "ipport:<dstport number>". That may help a bit but I understand that it's still suboptimal.

The last way to do this is via filtering on the API. You can take the result of the process query in an API script and look for the timestamp on all the resulting segments to filter through and find the specific item of interest. This of course requires some scripting, and can't be done directly through a deep link to the Cb web UI.

**Comment by jgarman** [comment]
Partially addressed this in the new OUTPUT.md documentation, but this could be further improved with the use of queries instead of direct links in some cases

**Comment by adamsmutnicki** [comment]
Hi Jason,
None of those solutions will work in my case. Searching API for each netconn you found out in QRadar and you are interested in is not a convenient way. 
Just to make sure I understand the problem correctly. Netconn is broadcasted on the MQTT, where it is picked up and stored, and this is when a segment_id is determined. But event forwarder picks up netconn (not yet stored) from MQTT and we do not know segment_id. 
Isn't there a possibility to broadcast a netconn stored event (from CB), like binary store event, and then catch new events on the other side, when they have been stored, not when they arrive to the server?
Thanks
Adam

**Comment by jgarman** [comment]
Adam,

Right now there is no such event type. Unfortunately that would require a product change- not something that can be requested here. Please submit a support request through Cb support on the [User eXchange](https://community.carbonblack.com).
